using System;
using System.Linq;
using tana_gh.UnityDotG.Editor;

namespace tana_gh.Mancala.Editor
{
    [CodeGen]
    public class EntryPointCodeGen
    {
        public static void Generate(CodeGenContext context)
        {
            context.AutoGeneratedFolder = UnityDotGConstants.AutoGeneratedFolder;

            foreach (var sceneKind in Enum.GetValues(typeof(SceneKind)).Cast<SceneKind>())
            {
                GenerateOne(context, sceneKind);
            }
        }

        public static void GenerateOne(CodeGenContext context, SceneKind sceneKind)
        {
            var handlers = RoleAttributeUtil.GetAllTypesWithRole("Handler", sceneKind);

            context.AddCode($"{sceneKind}EntryPoint.g.cs",
$@"
using VContainer;

namespace tana_gh.Mancala
{{
    public partial class {sceneKind}EntryPoint
    {{{
        handlers
        .Select(handler => $@"[Inject] private {handler.GetTypeName()} {handler.GetVarName(true)} {{ get; set; }}")
        .ToLines(8)
    }

        partial void Init()
        {{{
            handlers
            .Select(handler => $@"{handler.GetVarName(true)}.Init();")
            .ToLines(12)
        }
        }}
    }}
}}
"
            );
        }
    }
}
