// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;
using VContainer.Unity;
using MessagePipe;

namespace tana_gh.Mancala
{
    public partial class GameLifetimeScope
    {
        protected override void Configure(IContainerBuilder builder)
        {
            base.Configure(builder);
        
            builder.Register<EntityStore<Game>>(Lifetime.Scoped);
            builder.Register<EntityStore<Player>>(Lifetime.Scoped);
            builder.Register<EntityStore<Board>>(Lifetime.Scoped);
            builder.Register<EntityStore<Pocket>>(Lifetime.Scoped);
            builder.Register<EntityStore<Stone>>(Lifetime.Scoped);
            builder.Register<GameHandler>(Lifetime.Scoped);
            builder.Register<GameManager>(Lifetime.Scoped);
            var options = builder.RegisterMessagePipe();
            builder.RegisterMessageBroker<MessagesQueuingMessage>(options);
            builder.RegisterMessageBroker<NewGameStartingMessage>(options);
            builder.RegisterMessageBroker<PocketSelectedMessage>(options);
            builder.RegisterMessageBroker<StoneSelectedMessage>(options);
            builder.RegisterMessageBroker<DrewMessage>(options);
            builder.RegisterMessageBroker<NewGameStartedMessage>(options);
            builder.RegisterMessageBroker<PlayerDroppedStoneIntoPocketMessage>(options);
            builder.RegisterMessageBroker<PlayerDroppingStoneIntoPocketMessage>(options);
            builder.RegisterMessageBroker<PlayerGoaledAllStonesMessage>(options);
            builder.RegisterMessageBroker<PlayerGoaledMoreThanHalfStonesMessage>(options);
            builder.RegisterMessageBroker<PlayerJustGoaledMessage>(options);
            builder.RegisterMessageBroker<PlayerStolePocketMessage>(options);
            builder.RegisterMessageBroker<PlayerWonMessage>(options);
            builder.RegisterMessageBroker<WaitingPlayerTurnMessage>(options);
            builder.RegisterEntryPoint<GameEntryPoint>();
        }
    }
}
