// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.Mancala
{
    public partial class GameEntryPoint
    {
        [Inject] private IObjectResolver Resolver { get; set; }

        partial void Init()
        {
        }
    }
}
