// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.Mancala
{
    public partial class GameEntryPoint
    {
        [Inject] private GameHandler GameHandler { get; set; }
        [Inject] private GameManager GameManager { get; set; }

        partial void Init()
        {
            GameHandler.Init();
            GameManager.Init();
        }
    }
}
