// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.Mancala
{
    public partial class RootEntryPoint
    {

        partial void Init()
        {
        }
    }
}
