// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;
using VContainer.Unity;
using MessagePipe;

namespace tana_gh.Mancala
{
    public partial class RootLifetimeScope
    {
        protected override void Configure(IContainerBuilder builder)
        {
            base.Configure(builder);
        
            builder.RegisterEntryPoint<RootEntryPoint>();
        }
    }
}
